{% set name = "imaris-ims-file-reader" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/imaris_ims_file_reader-{{ version }}.tar.gz
  sha256: 357e48262236ac534a9c8e0cedffb983a66cdaa32d097ed5b47dd85ca62672d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - h5py >=3.5.0
    - numcodecs
    - numpy
    - python >={{ python_min }}
    - scikit-image
    - zarr

test:
  imports:
    - imaris_ims_file_reader
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CBI-PITT/imaris_ims_file_reader
  summary: Class for reading Bitplane imaris files (*.ims)
  license: BSD-3-Clause
  license_file: LICENCE

extra:
  recipe-maintainers:
    - goanpeca
